### ISSUE TITLE
how to parse

### ISSUE THREAD

**Issue by IRGC** [ndunks/php-simple-protobuf#1]
how to parse protobuf response ? please provide any sample.

**Comment by ndunks** [comment]
checkout on test directory, look on this file: https://github.com/ndunks/php-simple-protobuf/blob/master/test/MessageTest.php

**Comment by IRGC** [comment]
i tried but its not working :(  can this be used with google play proto file?

**Comment by ndunks** [comment]
Yes you can. I make it for google play proto, because I can't find Protobuf php that can work with playstore proto. You can check my project that used this repo on apkleecher.net and apk.web.id.
Can you give some attachment about your problem?

**Comment by IRGC** [comment]
how to compile .proto file into php classes on linux?
can you show an example?

**Comment by ndunks** [comment]
goto root dir and try execute this:

Creating output dir:
`mkdir result`

Compile simple.proto:
`php bin/compiler.php --out=result --file=test/proto/simple.proto`

**Comment by IRGC** [comment]
`PHP Warning:  include(/root/pb/vendor/ndunks/php-simple-protobuf/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 3
PHP Warning:  include(): Failed opening '/root/pb/vendor/ndunks/php-simple-protobuf/bin/../vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 3
PHP Fatal error:  Uncaught Error: Class 'kc\proto\compiler\Console' not found in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php:5
Stack trace:
#0 {main}
  thrown in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 5
`
i did same as you said but errors.

**Comment by ndunks** [comment]
Make sure  [composer](https://getcomposer.org) installed on your system.
Check if composer installed:
`
composer --version
`
if you get output like
`
Composer version 1.5.1 2017-08-09 16:07:22
`
it mean composer is installed.
then goto root dir (must contain file 'composer.json') and run this to install depencies:
`
composer install
`
Wait until done, then run the test:
`
php bin/compiler.php --out=result --file=test/proto/simple.proto
`

**Comment by IRGC** [comment]
the bin directory is inside the vendor directory not in the root directory.

**Comment by IRGC** [comment]
i have followed your steps it still not working.
can i contact you through any other channel?

**Comment by ndunks** [comment]
ah yes, you can try bin in vendor dir
`php vendor/bin/compiler.php`
I think we have different timezone so I can't quickly reply on other channel too

**Comment by IRGC** [comment]
still not working :disappointed:

**Comment by IRGC** [comment]
still same error
` php vendor/bin/compiler.php --out=result --file=GooglePlay.proto
PHP Warning:  include(/root/pb/vendor/ndunks/php-simple-protobuf/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 3
PHP Warning:  include(): Failed opening '/root/pb/vendor/ndunks/php-simple-protobuf/bin/../vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 3
PHP Fatal error:  Uncaught Error: Class 'kc\proto\compiler\Console' not found in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php:5
Stack trace:
#0 {main}
  thrown in /root/pb/vendor/ndunks/php-simple-protobuf/bin/compiler.php on line 5
`

**Comment by IRGC** [comment]
can you please help?

**Comment by ndunks** [comment]
Example Setup & installation on Linux
make sure your php.ini (cli) has `short_open_tag` is `On`

```
git clone https://github.com/ndunks/php-simple-protobuf
cd php-simple-protobuf
composer dump-autoload
```
You can skip `composer install` if you want to use it (not develop it) because this project not depend to any other composer library.
Run this to compile example proto (on project dir)
```
# if output directory not exist, you must create it manualy
mkdir result
# Compile it
php bin/compiler.php --out=result --file=test/proto/simple.proto
```
Check on result dir, you will get `Simple.php` file generated from `simple.proto`
